package main

import (
	"bufio"
	"context"
	"encoding/json"
	"flag"
	"fmt"
	"io"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
	"time"

	"github.com/bynine/godot-mcp-go/internal/ui"
)

// The cold test runner. `test` generates a MainLoop script into the project's
// .godot/, runs one headless engine over it with the test files as user args,
// reads the structured line the runner prints, and deletes the script again.
//
// Why MainLoop rather than SceneTree, which is what a hand-rolled `godot -s
// cli.gd` usually extends: the engine instantiates the project's autoloads only
// when the main loop is a SceneTree. Verified on 4.7.2 against this repo's own
// test project, whose autoloads bound a WebSocket port and wrote the game
// discovery file during a SceneTree run, which is exactly the kind of side
// effect a pure-logic test run must not have. A MainLoop run printed none of
// it. The cost is that a test cannot reach an autoload singleton; it loads the
// autoload's script and instantiates it instead, which is the pure-logic form
// anyway.

// testRunnerMarker prefixes the runner's stderr span markers, which is how a
// script error the engine printed gets attributed to the test that caused it:
// markers and diagnostics share the stderr stream, so their order survives
// whatever buffering stdout is under.
const testRunnerMarker = "##GDMCP-TEST##"

// testRunnerResult prefixes the one JSON line the runner prints to stdout. The
// prefix is what makes the line findable in a stream the project's own print()
// calls also write to.
const testRunnerResult = "##GDMCP-TEST-RESULT##"

// testRunnerName is the generated runner's filename under .godot/, which is
// git-ignored and session-scoped, so the file is invisible to the project even
// in the window before it is deleted.
const testRunnerName = "godot-mcp-test-runner.gd"

// testRunnerScript is the runner, generated verbatim on every run. It is an
// implementation detail of this subcommand: the contract users write against is
// the harness API below (ok/eq/ne/fail) and the test_* naming, both documented
// in the subcommand's help.
const testRunnerScript = `extends MainLoop
# Generated by godot-mcp test. Rewritten on every run, deleted when it ends.
#
# MainLoop, not SceneTree: the engine adds the project's autoloads only for a
# SceneTree main loop, and a pure-logic test run must not start them.

const MARK := "##GDMCP-TEST##"
const RESULT := "##GDMCP-TEST-RESULT##"

class Harness extends RefCounted:
	var failures: Array[String] = []

	func ok(cond: bool, msg: String = "") -> bool:
		if cond:
			return true
		failures.append(msg if msg != "" else "expected a true value")
		return false

	func eq(actual: Variant, expected: Variant, msg: String = "") -> bool:
		if actual == expected:
			return true
		failures.append(_label(msg) + "expected %s, got %s" % [_show(expected), _show(actual)])
		return false

	func ne(actual: Variant, other: Variant, msg: String = "") -> bool:
		if actual != other:
			return true
		failures.append(_label(msg) + "expected anything but %s" % _show(other))
		return false

	func fail(msg: String) -> void:
		failures.append(msg)

	func _label(msg: String) -> String:
		return "" if msg == "" else msg + ": "

	func _show(v: Variant) -> String:
		return "%s (%s)" % [var_to_str(v), type_string(typeof(v))]


func _initialize() -> void:
	var files: Array = []
	for path in OS.get_cmdline_user_args():
		var entry := {"path": path, "loaded": false, "error": "", "tests": []}
		files.append(entry)
		_run_file(path, entry)
	print(RESULT + JSON.stringify({"files": files}))


func _process(_delta: float) -> bool:
	return true


# A GDScript error aborts the function it happens in, so every step that can
# raise one sets the message it would leave behind before it runs, and clears
# it after. That way an abort still reports why, rather than dropping the file.
func _run_file(path: String, entry: Dictionary) -> void:
	entry["error"] = "could not load %s" % path
	printerr("%s load %s" % [MARK, path])
	var script: Variant = load(path)
	printerr("%s idle" % MARK)
	if script == null or not (script is GDScript):
		return
	if not script.can_instantiate():
		entry["error"] = "%s did not compile" % path
		return
	entry["error"] = "%s could not be instantiated: a test script must extend RefCounted and take no _init arguments" % path
	var obj: Object = script.new()
	if obj == null:
		return
	entry["error"] = ""
	entry["loaded"] = true
	for info in _tests_of(obj):
		var mname: String = info["name"]
		var argc: int = info["argc"]
		if argc > 1:
			entry["tests"].append({
				"name": mname, "ok": false, "duration_ms": 0.0,
				"failures": ["takes %d arguments; a test method takes none, or one for the harness" % argc],
			})
			continue
		var h := Harness.new()
		printerr("%s test %s %s" % [MARK, path, mname])
		var started := Time.get_ticks_usec()
		if argc == 1:
			obj.call(mname, h)
		else:
			obj.call(mname)
		var micros := Time.get_ticks_usec() - started
		printerr("%s idle" % MARK)
		entry["tests"].append({
			"name": mname,
			"ok": h.failures.is_empty(),
			"failures": h.failures,
			"duration_ms": micros / 1000.0,
		})
	if obj is Node:
		obj.free()


func _tests_of(obj: Object) -> Array:
	var seen := {}
	var out: Array = []
	for m in obj.get_method_list():
		var mname: String = m["name"]
		if not mname.begins_with("test_") or seen.has(mname):
			continue
		seen[mname] = true
		out.append({"name": mname, "argc": (m["args"] as Array).size()})
	out.sort_custom(func(a, b): return a["name"] < b["name"])
	return out
`

// testCase is one test method's verdict: what the harness recorded, plus any
// diagnostic the engine printed while that method ran.
type testCase struct {
	Name       string           `json:"name"`
	OK         bool             `json:"ok"`
	DurationMS float64          `json:"duration_ms"`
	Failures   []string         `json:"failures"`
	Errors     []engineLogEntry `json:"errors"`
}

// testFileResult is one test file's verdict. Error is set when the file never
// got as far as running anything (a parse error, or a script that cannot be
// instantiated), and Errors then carries the engine's own message for it.
type testFileResult struct {
	Path   string           `json:"path"`
	OK     bool             `json:"ok"`
	Loaded bool             `json:"loaded"`
	Error  string           `json:"error,omitempty"`
	Errors []engineLogEntry `json:"errors"`
	Tests  []testCase       `json:"tests"`
}

// testResult is the JSON shape of `test --json` (and of piped output).
type testResult struct {
	ProjectPath string           `json:"project_path"`
	Command     []string         `json:"command"`
	Log         string           `json:"log"`
	Files       int              `json:"files"`
	FilesFailed int              `json:"files_failed"`
	Total       int              `json:"total"`
	Passed      int              `json:"passed"`
	Failed      int              `json:"failed"`
	DurationMS  int64            `json:"duration_ms"`
	Results     []testFileResult `json:"results"`
}

// runTest is a local subcommand that runs pure-logic GDScript tests cold: one
// headless engine, no editor, no scene tree, no autoloads. It completes the
// cold set alongside import, check, launch, run and export.
//
// It does not refuse while an editor is open. The run reads the project's
// scripts and writes nothing but its own generated runner under .godot/, so
// there is no cache to fight over the way a headless import would.
func runTest(args []string) int {
	fs := flag.NewFlagSet("test", flag.ContinueOnError)
	project := fs.String("project", "", "Godot project dir (default: the project containing the cwd)")
	timeout := fs.Duration("timeout", 5*time.Minute, "how long to let the run take")
	godot := fs.String("godot", "", "path to the Godot binary (default: godot on PATH)")
	asJSON := fs.Bool("json", false, "emit the result as JSON instead of a human summary")
	fs.Usage = subHelp(fs, "run pure-logic GDScript tests cold, with no editor",
		[]string{"godot-mcp test [dir|file]... [--project DIR] [--timeout 5m] [--godot PATH] [--json]"},
		`Runs one headless engine over a generated runner script and reports every
test method's verdict. With no path it takes res://test/, walked recursively for
files named *_test.gd or test_*.gd; a path you name may be a directory or a
single file, spelled res:// or relative to the cwd.

The test contract, which needs nothing installed in the project:

  extends RefCounted

  func test_gold_becomes_coins(t) -> void:
      var save := migrate({"version": 1, "gold": 30})
      t.eq(save["coins"], 30, "gold carried over")
      t.ok(not save.has("gold"), "gold key dropped")

A test file is any script that extends RefCounted (anything instantiable with
no arguments works) and every method named test_* is a test. The method takes
one argument, the harness, or none at all. The harness records failures and
keeps going, so one method can report several:

  t.ok(cond, msg)          fails unless cond is true
  t.eq(actual, expected, msg)
  t.ne(actual, other, msg)
  t.fail(msg)              records msg unconditionally

A test also fails when the engine prints a script error while it runs, and a
file that does not parse is reported as one failed file with the parse message.

The run is cold and synchronous: no editor, no scene tree, and the project's
autoloads are never started, so a test loads and instantiates what it needs.
It is read-only, so an open editor is fine and nothing about this command
touches it.

The full engine output goes to <project>/.godot/godot-mcp-test.log.

Exit 0 when everything passed, 1 when anything failed, 2 when the run could not
be set up or produced no report.`)
	positional, prc := parseSubPositional(fs, args)
	if prc >= 0 {
		return prc
	}

	root, rerr := projectRootFor(*project)
	if rerr != nil {
		fmt.Fprintf(os.Stderr, "%s %v\n", ui.Err.Fail("error:"), rerr)
		return 2
	}

	targets := positional
	if len(targets) == 0 {
		def := filepath.Join(root, "test")
		if info, serr := os.Stat(def); serr != nil || !info.IsDir() {
			fmt.Fprintf(os.Stderr, "%s no res://test/ directory in %s\n", ui.Err.Fail("error:"), root)
			fmt.Fprintln(os.Stderr, "Put pure-logic tests in res://test/ as *_test.gd or test_*.gd, or name a path: godot-mcp test res://scripts/save")
			return 2
		}
		targets = []string{def}
	}

	files, cerr := collectTestFiles(root, targets)
	if cerr != nil {
		fmt.Fprintf(os.Stderr, "%s %v\n", ui.Err.Fail("error:"), cerr)
		return 2
	}
	if len(files) == 0 {
		fmt.Fprintf(os.Stderr, "%s no *_test.gd or test_*.gd files under %s\n", ui.Err.Warn("warning:"), strings.Join(targets, ", "))
		return 0
	}

	bin, berr := resolveGodotBinary(*godot)
	if berr != nil {
		fmt.Fprintf(os.Stderr, "%s %v\n", ui.Err.Fail("error:"), berr)
		return 2
	}

	runnerPath := filepath.Join(root, ".godot", testRunnerName)
	if err := os.MkdirAll(filepath.Dir(runnerPath), 0o755); err != nil {
		fmt.Fprintf(os.Stderr, "%s creating %s: %v\n", ui.Err.Fail("error:"), filepath.Dir(runnerPath), err)
		return 2
	}
	if err := os.WriteFile(runnerPath, []byte(testRunnerScript), 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "%s writing the runner to %s: %v\n", ui.Err.Fail("error:"), runnerPath, err)
		return 2
	}
	defer os.Remove(runnerPath)

	argv := testArgs(root, "res://.godot/"+testRunnerName, files)
	logPath := godotLogPath(root, "test")

	ctx, cancel := context.WithTimeout(context.Background(), *timeout)
	defer cancel()
	_, elapsed, xerr := runGodotWait(ctx, bin, root, logPath, argv)
	if xerr != nil {
		fmt.Fprintf(os.Stderr, "%s could not run %s: %v\n", ui.Err.Fail("error:"), bin, xerr)
		return 2
	}

	log, lerr := os.Open(logPath)
	if lerr != nil {
		fmt.Fprintf(os.Stderr, "%s reading %s: %v\n", ui.Err.Fail("error:"), logPath, lerr)
		return 2
	}
	report, spans, perr := readTestLog(log)
	_ = log.Close()

	res := testResult{
		ProjectPath: root,
		Command:     append([]string{bin}, argv...),
		Log:         logPath,
		DurationMS:  elapsed.Milliseconds(),
	}

	if perr != nil {
		if ctx.Err() != nil {
			fmt.Fprintf(os.Stderr, "%s the run did not finish within %s; see %s\n", ui.Err.Fail("error:"), *timeout, logPath)
			return 1
		}
		fmt.Fprintf(os.Stderr, "%s %v; see %s\n", ui.Err.Fail("error:"), perr, logPath)
		for _, e := range spans[""] {
			fmt.Fprintln(os.Stderr, "  "+e.String())
		}
		return 2
	}

	res.Results = mergeTestReport(files, report, spans)
	res.Files = len(res.Results)
	for _, f := range res.Results {
		// files_failed counts the files that never ran a test at all, so it
		// stays a separate number from the methods that ran and failed.
		if f.Error != "" {
			res.FilesFailed++
		}
		for _, tc := range f.Tests {
			res.Total++
			if tc.OK {
				res.Passed++
			} else {
				res.Failed++
			}
		}
	}

	rc := 0
	line := fmt.Sprintf("%d tests passed in %s", res.Total, elapsed.Round(time.Millisecond))
	if res.Failed > 0 || res.FilesFailed > 0 {
		rc = 1
		var parts []string
		if res.Failed > 0 {
			parts = append(parts, fmt.Sprintf("%d of %d tests failed", res.Failed, res.Total))
		}
		if res.FilesFailed > 0 {
			parts = append(parts, fmt.Sprintf("%d of %d files could not be run", res.FilesFailed, res.Files))
		}
		line = strings.Join(parts, ", ")
	}
	if ctx.Err() != nil {
		line = fmt.Sprintf("the run did not finish within %s; see %s", *timeout, logPath)
		rc = 1
	}

	emitResult("test", res, *asJSON, line, [][2]string{
		{"project", res.ProjectPath},
		{"files", strconv.Itoa(res.Files)},
		{"tests", strconv.Itoa(res.Total)},
		{"passed", strconv.Itoa(res.Passed)},
		{"failed", strconv.Itoa(res.Failed)},
		{"duration", elapsed.Round(time.Millisecond).String()},
		{"log", res.Log},
	})
	printTestFailures(res.Results)
	return rc
}

// printTestFailures writes the failing files and methods to stderr, the way
// check reports the files that would not parse.
func printTestFailures(results []testFileResult) {
	for _, f := range results {
		if f.OK {
			continue
		}
		fmt.Fprintln(os.Stderr, ui.Err.Fail(f.Path))
		if f.Error != "" {
			fmt.Fprintln(os.Stderr, "  "+f.Error)
		}
		for _, e := range f.Errors {
			fmt.Fprintln(os.Stderr, "  "+e.String())
		}
		for _, tc := range f.Tests {
			if tc.OK {
				continue
			}
			fmt.Fprintln(os.Stderr, "  "+ui.Err.Warn(tc.Name))
			for _, msg := range tc.Failures {
				fmt.Fprintln(os.Stderr, "    "+msg)
			}
			for _, e := range tc.Errors {
				fmt.Fprintln(os.Stderr, "    "+e.String())
			}
		}
	}
}

// testArgs builds the child's argv. Everything after ++ is what the runner
// reads back with OS.get_cmdline_user_args(), which is how the file list
// crosses into the engine without a temp file of its own.
func testArgs(root, runner string, files []string) []string {
	args := []string{"--headless", "--path", root, "--script", runner, "++"}
	return append(args, files...)
}

// isTestScript reports whether a filename is one of the two conventions the
// default sweep recognises. Both are in the wild and neither is more correct,
// so a project that has picked one is never told it picked wrong.
func isTestScript(name string) bool {
	lower := strings.ToLower(name)
	if !strings.HasSuffix(lower, ".gd") {
		return false
	}
	base := strings.TrimSuffix(lower, ".gd")
	return strings.HasSuffix(base, "_test") || strings.HasPrefix(base, "test_")
}

// collectTestFiles expands the caller's paths into res:// script paths, sorted
// and deduplicated. A directory is walked for the two test-file conventions; a
// named file is taken as given, since naming it is the statement that it is a
// test whatever it is called.
func collectTestFiles(root string, paths []string) ([]string, error) {
	seen := map[string]bool{}
	for _, p := range paths {
		local, err := localPath(root, p)
		if err != nil {
			return nil, err
		}
		info, serr := os.Stat(local)
		if serr != nil {
			return nil, fmt.Errorf("%s: %w", p, serr)
		}
		if !info.IsDir() {
			if !strings.EqualFold(filepath.Ext(local), ".gd") {
				return nil, fmt.Errorf("%s is not a .gd file", p)
			}
			res, rerr := toResPath(root, local)
			if rerr != nil {
				return nil, rerr
			}
			seen[res] = true
			continue
		}
		skipAddons := !underAddons(root, local)
		werr := filepath.WalkDir(local, func(path string, d fs.DirEntry, err error) error {
			if err != nil {
				return err
			}
			if d.IsDir() {
				name := d.Name()
				if name == ".godot" || (skipAddons && name == "addons") {
					return filepath.SkipDir
				}
				return nil
			}
			if !isTestScript(d.Name()) {
				return nil
			}
			res, rerr := toResPath(root, path)
			if rerr != nil {
				return rerr
			}
			seen[res] = true
			return nil
		})
		if werr != nil {
			return nil, werr
		}
	}
	out := make([]string, 0, len(seen))
	for p := range seen {
		out = append(out, p)
	}
	sort.Strings(out)
	return out, nil
}

// runnerReport is the JSON the runner prints. It is the runner's own shape, kept
// separate from testResult so the wire format and the reported result can move
// independently.
type runnerReport struct {
	Files []struct {
		Path   string `json:"path"`
		Loaded bool   `json:"loaded"`
		Error  string `json:"error"`
		Tests  []struct {
			Name       string   `json:"name"`
			OK         bool     `json:"ok"`
			DurationMS float64  `json:"duration_ms"`
			Failures   []string `json:"failures"`
		} `json:"tests"`
	} `json:"files"`
}

// readTestLog reads one engine run's merged output and returns the runner's
// report plus the diagnostics printed inside each marked span. The two are
// independent passes over the same lines: the report is one prefixed line
// anywhere in the stream, the spans are the stderr markers with the engine's
// own ERROR and SCRIPT ERROR lines between them.
func readTestLog(r io.Reader) (*runnerReport, map[string][]engineLogEntry, error) {
	spans := map[string][]string{}
	key := ""
	payload := ""

	sc := bufio.NewScanner(r)
	sc.Buffer(make([]byte, 0, 64*1024), 8*1024*1024)
	for sc.Scan() {
		line := sc.Text()
		trimmed := strings.TrimSpace(line)
		if rest, ok := strings.CutPrefix(trimmed, testRunnerMarker); ok {
			key = spanKey(strings.TrimSpace(rest))
			continue
		}
		if rest, ok := strings.CutPrefix(trimmed, testRunnerResult); ok {
			payload = rest
			continue
		}
		spans[key] = append(spans[key], line)
	}
	if serr := sc.Err(); serr != nil {
		return nil, nil, fmt.Errorf("reading the engine log: %w", serr)
	}

	entries := map[string][]engineLogEntry{}
	for k, lines := range spans {
		errs, _ := splitEngineLog(parseEngineLog(strings.NewReader(strings.Join(lines, "\n"))))
		if len(errs) > 0 {
			entries[k] = errs
		}
	}
	if payload == "" {
		return nil, entries, fmt.Errorf("the test runner produced no report")
	}
	var report runnerReport
	if jerr := json.Unmarshal([]byte(payload), &report); jerr != nil {
		return nil, entries, fmt.Errorf("the test runner's report did not parse: %w", jerr)
	}
	return &report, entries, nil
}

// spanKey turns a marker's payload into the key its diagnostics are filed
// under: "load <path>" for a file's load, "<path>::<method>" for a test, and
// the empty key for anything printed outside a span.
func spanKey(rest string) string {
	kind, arg, _ := strings.Cut(rest, " ")
	switch kind {
	case "load":
		return "load " + arg
	case "test":
		path, method, ok := strings.Cut(arg, " ")
		if !ok {
			return ""
		}
		return path + "::" + method
	default:
		return ""
	}
}

// mergeTestReport joins the runner's verdicts to the diagnostics the engine
// printed, walking the requested file list so the output order is the order
// asked for and a file the runner never reached shows up as a failure rather
// than vanishing.
func mergeTestReport(requested []string, report *runnerReport, spans map[string][]engineLogEntry) []testFileResult {
	byPath := map[string]int{}
	for i, f := range report.Files {
		if f.Path != "" {
			byPath[f.Path] = i
		}
	}
	out := make([]testFileResult, 0, len(requested))
	for _, path := range requested {
		f := testFileResult{Path: path, Errors: orEmpty(spans["load "+path]), Tests: []testCase{}}
		i, ok := byPath[path]
		if !ok {
			f.Error = "the runner produced no result for this file"
			out = append(out, f)
			continue
		}
		src := report.Files[i]
		f.Loaded = src.Loaded
		f.Error = src.Error
		f.OK = src.Error == ""
		for _, tsrc := range src.Tests {
			tc := testCase{
				Name:       tsrc.Name,
				OK:         tsrc.OK,
				DurationMS: tsrc.DurationMS,
				Failures:   tsrc.Failures,
				Errors:     orEmpty(spans[path+"::"+tsrc.Name]),
			}
			if tc.Failures == nil {
				tc.Failures = []string{}
			}
			// A method that finished without recording a failure still fails if
			// the engine printed a script error while it ran: GDScript aborts
			// the call and hands control back, so the harness never sees it.
			if len(tc.Errors) > 0 {
				tc.OK = false
			}
			if !tc.OK {
				f.OK = false
			}
			f.Tests = append(f.Tests, tc)
		}
		out = append(out, f)
	}
	return out
}
