package main

import (
	"fmt"
	"regexp"
	"strings"
	"unicode"
)

const (
	blockHeading = "## Contents"
	blockStart   = "<!-- doc-index:start"
	blockEnd     = "<!-- doc-index:end -->"
	// A section longer than this also lists its ### subsections, since a reader
	// limited to this many lines cannot take it in one read.
	readWindow = 100
)

// A closing run of #s needs a space before it, so "C#" keeps its #.
var headingRe = regexp.MustCompile(`^(#{1,6})\s+(.*?)(?:\s+#+)?\s*$`)

type heading struct {
	level  int
	title  string
	line   int // 0-based
	anchor string
}

// Render returns text with its Contents block regenerated. A doc with fewer
// than two sections gets no block. Line endings are preserved.
func Render(text string) string {
	crlf := strings.Contains(text, "\r\n")
	lines := strings.Split(strings.ReplaceAll(text, "\r\n", "\n"), "\n")
	lines, kept := stripBlock(lines)

	heads := parseHeadings(lines)
	at, heads := insertionPoint(lines, heads)
	if kept >= 0 {
		at = kept // a block moved by hand stays where it was put
	}

	var entries []heading
	for i, h := range heads {
		if h.level <= 2 || (h.level == 3 && parentLength(heads, i, lines) > readWindow) {
			entries = append(entries, h)
		}
	}

	out := lines
	if countTop(entries) >= 2 {
		// Block lines: heading, blank, start comment, entries, end comment, blank.
		shift := len(entries) + 5
		total := len(lines) + shift
		if lines[len(lines)-1] == "" {
			total-- // trailing newline, not a line
		}
		block := []string{
			blockHeading,
			"",
			fmt.Sprintf("%s %d lines. Read one section by its range: offset=start, limit=end-start+1. Generated by go run ./tools/docindex; rerun it after editing headings. -->", blockStart, total),
		}
		n := 0
		moved := func(line int) int {
			if line >= at {
				return line + 1 + shift
			}
			return line + 1
		}
		for _, h := range entries {
			start, end := moved(h.line), moved(sectionEnd(heads, h, lines))
			title := strings.ReplaceAll(h.title, "]", `\]`)
			if h.level <= 2 {
				n++
				block = append(block, fmt.Sprintf("%d. [%s](#%s) (lines %d-%d)", n, title, h.anchor, start, end))
			} else {
				block = append(block, fmt.Sprintf("   - [%s](#%s) (lines %d-%d)", title, h.anchor, start, end))
			}
		}
		block = append(block, blockEnd, "")
		out = append(append(append([]string{}, lines[:at]...), block...), lines[at:]...)
	}

	result := strings.Join(out, "\n")
	if crlf {
		result = strings.ReplaceAll(result, "\n", "\r\n")
	}
	return result
}

// stripBlock removes an existing block (its heading, the generated list, and
// the blank line after it) and returns where it stood, or -1.
func stripBlock(lines []string) ([]string, int) {
	for i, l := range lines {
		if !strings.HasPrefix(l, blockStart) {
			continue
		}
		for j := i + 1; j < len(lines); j++ {
			if lines[j] != blockEnd {
				continue
			}
			from := i
			if from >= 2 && lines[from-1] == "" && lines[from-2] == blockHeading {
				from -= 2
			}
			if j+1 < len(lines) && lines[j+1] == "" {
				j++
			}
			return append(append([]string{}, lines[:from]...), lines[j+1:]...), from
		}
	}
	return lines, -1
}

// parseHeadings finds ATX headings outside fenced code blocks and gives each
// the anchor GitHub would.
func parseHeadings(lines []string) []heading {
	var heads []heading
	seen := map[string]int{}
	fence := ""
	for i, l := range lines {
		t := strings.TrimSpace(l)
		if fence != "" {
			if strings.HasPrefix(t, fence) {
				fence = ""
			}
			continue
		}
		if strings.HasPrefix(t, "```") || strings.HasPrefix(t, "~~~") {
			fence = t[:3]
			continue
		}
		if m := headingRe.FindStringSubmatch(l); m != nil {
			a := slug(m[2])
			if n := seen[a]; n > 0 {
				seen[a]++
				a = fmt.Sprintf("%s-%d", a, n)
			} else {
				seen[a] = 1
			}
			heads = append(heads, heading{len(m[1]), m[2], i, a})
		}
	}
	return heads
}

var linkRe = regexp.MustCompile(`\[([^\]]*)\]\([^)]*\)`)

// slug follows GitHub's heading anchors: link text kept, lowercased, spaces to
// hyphens, punctuation other than hyphen and underscore dropped.
func slug(title string) string {
	title = linkRe.ReplaceAllString(title, "$1")
	var b strings.Builder
	for _, r := range strings.ToLower(title) {
		switch {
		case r == ' ':
			b.WriteRune('-')
		case r == '-' || r == '_' || unicode.IsLetter(r) || unicode.IsDigit(r):
			b.WriteRune(r)
		}
	}
	return b.String()
}

// insertionPoint places the block after the title heading, or after front
// matter when there is no title, and drops the title from the headings.
func insertionPoint(lines []string, heads []heading) (int, []heading) {
	at := 0
	if len(heads) > 0 && heads[0].level == 1 {
		at = heads[0].line + 1
		heads = heads[1:]
	} else if len(lines) > 0 && lines[0] == "---" {
		for i := 1; i < len(lines); i++ {
			if lines[i] == "---" {
				at = i + 1
				break
			}
		}
	}
	if at > 0 && at < len(lines) && lines[at] == "" {
		at++
	}
	return at, heads
}

// sectionEnd is the last non-blank line before the next heading at the same
// or a higher level.
func sectionEnd(heads []heading, h heading, lines []string) int {
	end := len(lines) - 1
	for _, n := range heads {
		if n.line > h.line && n.level <= h.level {
			end = n.line - 1
			break
		}
	}
	for end > h.line && strings.TrimSpace(lines[end]) == "" {
		end--
	}
	return end
}

// parentLength is the line count of the section enclosing heads[i].
func parentLength(heads []heading, i int, lines []string) int {
	for p := i - 1; p >= 0; p-- {
		if heads[p].level < heads[i].level {
			return sectionEnd(heads, heads[p], lines) - heads[p].line + 1
		}
	}
	return 0
}

func countTop(entries []heading) int {
	n := 0
	for _, h := range entries {
		if h.level <= 2 {
			n++
		}
	}
	return n
}
